#! /bin/sh
set -e
set -x
echo $1
case "$1" in
  upgrade)
  if [ -f /usr/lib/libedata-cal-1.2.so.23 ]; then
    dpkg-divert --add --local --divert /usr/lib/libedata-cal-1.2.so.23.divert --rename /usr/lib/libedata-cal-1.2.so.23
  fi
  if [ -f /usr/lib/libedata-cal-1.2.so.23.0.0 ]; then
    dpkg-divert --add --local --divert /usr/lib/libedata-cal-1.2.so.23.0.0.divert --rename /usr/lib/libedata-cal-1.2.so.23.0.0 
  fi
esac

exit 0
