#! /bin/sh
set -e
set -x
echo $1
case "$1" in
  upgrade)
  if [ -f /usr/lib/libedata-book-1.2.so.20 ]; then
    dpkg-divert --add --local --divert /usr/lib/libedata-book-1.2.so.20.divert --rename /usr/lib/libedata-book-1.2.so.20
  fi
  if [ -f /usr/lib/libedata-book-1.2.so.20.0.0 ]; then
    dpkg-divert --add --local --divert /usr/lib/libedata-book-1.2.so.20.0.0.divert --rename /usr/lib/libedata-book-1.2.so.20.0.0
  fi
esac

exit 0
