#! /bin/sh
set -e
set -x
echo $1
case "$1" in
  upgrade)
  if [ -f /usr/lib/libebackend-1.2.so.7 ]; then
    dpkg-divert --add --local --divert /usr/lib/libebackend-1.2.so.7.divert --rename /usr/lib/libebackend-1.2.so.7
  fi
  if [ -f /usr/lib/libebackend-1.2.so.7.0.0 ]; then
    dpkg-divert --add --local --divert /usr/lib/libebackend-1.2.so.7.0.0.divert --rename /usr/lib/libebackend-1.2.so.7.0.0
  fi
esac

exit 0
